### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by 28niwa2108** [28niwa2108/furima-36323#21]
- フリマアプリのURL
https://furima-36323.herokuapp.com/
- Basic認証
ユーザー名：admin
パスワード：36323
- 出品者用情報
メールアドレス：seller@com
パスワード：sssss1
- 購入者用情報
メールアドレス：buyer@com
パスワード：bbbbb1

**Comment by snkw-works** [comment]
@28niwa2108 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **商品出品時とほぼ同じ見た目の商品情報編集ページが表示されるよう修正しましょう**
「編集ページ」にて、「商品の状態」の選択項目が正しく表示されていません。
<img width="585" alt="スクリーンショット_2021-11-06_17_12_50" src="https://user-images.githubusercontent.com/54050089/140603040-79dd7c94-b521-4cc3-a816-20d848263ba3.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by 28niwa2108** [comment]
挙動確認の実施、ありがとうございます！

見落としがあり、申し訳ございません。
ご指摘いただいた箇所について、修正致しました。
ご確認お願い申し上げます。

※再度データベースのリセットが必要な場合、
お手数ですがコメントで教えていただければ幸いです。

**Comment by snkw-works** [comment]
@28niwa2108 さん、フリマアプリ達成要件分の開発お疲れ様でした！
修正が確認でき、正常に動作することが確認できました！ **LGTM** です！　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

#### ＜今後の学習例＞
```
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
```
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。

また、以下提出物に関するリマインドです。

#### ＜提出物＞
```
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
```
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

#### ＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/6853

今後の流れに関して、もしご不明点がございましたら、担当ライフコーチまでお気兼ねなくお申し付けくださいませ。

![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/140603719-d6b7ff4a-483a-4ef8-ad17-1b0e41949f7d.png)
